# Generated by Django 6.0.1 on 2026-02-02 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZOMATODB',
            fields=[
                ('product_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('product_Name', models.CharField(max_length=25)),
                ('hotel_Name', models.CharField(max_length=25)),
                ('product_Price', models.IntegerField()),
                ('hotel_Rating', models.IntegerField()),
                ('product_category', models.CharField(max_length=20)),
                ('product_feedback', models.TextField()),
            ],
        ),
    ]
